#Comando para ejecutar:
  #docker-compose -f docker-compose-production.yml up
version: "3.8"

services:

  #------------------------------------------------------
  #-------------------- NODE SERVICE --------------------
  #------------------------------------------------------
  node:
    container_name: node
    image: "node:14"

    #Ejecuta el c칩digo que est치 en esta direcci칩n
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    ports:
      - "3000:3000" #Puerto del el front-end
      - "3001:3001" #Puerto para la API
      - "80:3002"   #Conexi칩n sin ssl

    #Creamos la carpeta node_modules solo por 1ra vez
    command: sh -c "npm install"