#Comando para ejecutar:
  #docker-compose -f docker-compose-production.yml up
version: "3.8"

services:

  #------------------------------------------------------
  #-------------------- NODE SERVICE --------------------
  #------------------------------------------------------
  node_install:
    container_name: node_install
    image: "node:14"

    #Ejecuta el código que está en esta dirección
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/app

    #Creamos la carpeta node_modules solo por 1ra vez
    command: sh -c "npm install"